server:
  port: 9999
  context-path: /admin-serverv
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mail:
    host: smtp.163.com
    username: 15811419781@163.com
    password: KSOGGFEQTYVQMCUW
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口
      port: 6379
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 0
  boot:
    admin:
      url: http://localhost:8080/admin-server
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer
      auto-offset-reset: latest
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.myspringboot.controller

logging:
  level:
    com:
      springboot:
        mapper: debug
management:
  security:
    enabled: false
  port: 9999
  context-path: /monitor
endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"